import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Next js is cool</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='main-container'>
        <ul>
          <li>
            <Link href="/fetch-user">
              Go to Fetch user
            </Link>
          </li>
        </ul>
      </main>
    </div>
  )
}

export default Home